# conf/config.yaml
defaults:
  - _self_
  - dir: local # デフォルトはlocal設定を使う
  - model: resnet18 # デフォルトのモデル
  - training: default
  - override hydra/job_logging: disabled # ログ設定の簡略化

# 実験名 (実行時に exp_name=xxx で上書きする想定)
exp_name: debug_run

# Hydraが出力するフォルダのルール設定
hydra:
  run:
    # output/実験名 のフォルダに結果を保存する
    dir: ${dir.output_dir}/${exp_name}
  sweep:
    dir: ${dir.output_dir}/${exp_name}
    subdir: ${hydra.job.num}
